apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager/

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.24.1
    includeCRDs: true
    releaseName: vault
    namespace: vault
    valuesFile: vault-values.yaml

  - name: minio
    repo: https://charts.min.io/
    version: 5.0.8
    includeCRDs: true
    releaseName: minio
    namespace: minio
    valuesFile: minio-values.yaml