persistence:
  size: 50Gi

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/issuer: "letsencrypt-prd"
  ingressClassName: "nginx"
  hosts:
    - minio.ounu.ch
  tls:
    - secretName: minio.ounu.ch-tls
      hosts:
        - minio.ounu.ch